[package]
name = "crabcan"
version = "0.1.0"
authors = ["Deane Leung"]
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
log = "0.4"
env_logger = "0.9"
nix = "0.25"
scan_fmt = "0.2"
